language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: meet-in-the-middle-frontend
  api_key:
    secure: Oc0e/oNNuujXU4QN+uZyA4vdmYwuGvGPY2g2w906LTHUu9pwkIpxnDlbLEY/cCvouQawXcpqYcA1x1RHXlnKLThTCopXGuiUXjEOWoz4sIq/Z7ohAErZpxj6eyiLggnQ9sJmYjzvBNYFT9PDWFe6NmslImg7v1qqJC10JDfu5VISzmaWuEnrTxarCTnkjzRkkU1ymdfBareFDLmXZMBJu2PUWtFUk4HMxuxJiE8NWKA/hcI6JelZ3k/+ZpX69iFz2bcHb/qgZINVYfOSMDrnj2aWei1GWGTWy+ttiXTBa5AGQxjP8Fsv3E95h4hbUA69hjZoPkSl33bs1ZAnLm2rJuxsMqlRoPX97/WqDqNtaTb9JsJUFJGPjuWATIs+D2YgcplEPGM6zR+f4H0n0PTNI6cyIMYnox28xibdMeR+254VQ113jAKNa9qRtulHcgluyXVSqCuwjy77H6ZZ8pa1LMRYZY3yYJ3wbEdOdqI2AJfQQPeYJ7vM2rAKpgb7h9a5EoU9iA5oo98X1nq3KrtbsDn1JcicewwG4JZlNnRDtEH8KaVN10f5xIK9Gg4euGxf48leoiiiqctPdcEmL45d7kM3MiIKqQw6pfu8kmIMmczF9XPFQE1LuymAvp9RUInNSsSp7dQ/y4qREq/VhI0unCkoJZAtrAUGx4K1npp/IjI=
