language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: meet-in-the-middle-frontend
  api_key:
    secure: BKsH6DbapYba3IEGKxF3wIFz5dgs0XQr4tMnYohJJ+lHdie21lhlt6RqvvLgTgpqsmdZ13bRBchD2wsEs8unBjjq7bzp6/nZDJkcuK6OM0aw7uRzZfpOHaL8vFzBpcf+cy2puwUGxquc3j7ycgZdW8CEM3Y18JBVrCOc8mACcopoTsfrV/PMLpm+MilLLLcpl7x5UaNsCtEQKbykOjhV+/4b1E74VUwq3te1IlKE+blW68YpT/FIqdy+qph2RLVxZaMLtFWXtn4RPGIxitCKkMvaaDXZylBy3lnzPoIk/O/0QnrhfunI2deks7Iby8navMG4dg6emQ0YDQWCakiWEM3RAVQVJePcpTlsDOaBMNOHgnIVxZrwKRKz2sZA53iI59gnRGm+XTOXX2fUV0Dijsd3QfvBMeFfgSHSxXrptv9UVnsvuFVlGYZiWCdIAVZm7fr145vhHVx/qoJkATZF7/aS4Lxrxiu6cThtrzZSyYcoVHMY/ZcTD2zI5OQYsgqZSbG0vIrv3zUwxWFdYEN8pOvfCt0t3nmzmGELygLQRmf2X4Z02qMRR2F1Mg+3jUx42ppcUi6fF/Phhkabc/IV5XFM29+U+ienKWEqn78KL9Tc3Z7jpGxxiAbKDVXeyFtpEOSrKg6cuyNu3X//eQWKjlQZVT6v9jJgBTfVeuJPwCs=
