language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ozc9Jecx9DdsIfsHsIBTUzd3VwF+pSoHeFipKZD8vJRJZTGkdXqXvNc6rhARrHN76YZWHpKHSOKsIEdb8dZDWJ/DZ0LX7jtgO/2nLjWXcqynQE0DJ0OrITrVY0yxyXB7M2uaag5D+ZlQbmqZHJa0oTpJLEac1u213aVp+CWn2LK4H20VCSlrxKhV3c7jiUDEETziK0202AM+tTIBdxdYdMkslYQnSPSrppPxx6/969T9nxI396+tF4BgnxFc5nRXMQmjr367xpxRRkRlc0VhPO3s8GYc88/KsP3LBc7wiSOY3Id6lSNPweew+vj6gPi8QJQWv7vTQH1S+46P4WUY/VcaDjOiTBMYyxz6j4VDMgdq0QoUReiFB5px5ARsJEVylgocznWUY3K5xd1PrHN6jWABVzedG+katLBIUTcGjuPF3hZ3vZRpDmzgP5qNMqJncEE7sm2YfjyjkFJaFu1DqjG2/ln1lsQ+fRIgB+Vkgo/duP2UIi6AXWztQIJTedB9mH5r0JIvzQFQMEPGZszRtlmh2IBNwynYL0PWDKdhNpTVgkANWgew/v656vEojqdYoDee4naMflGzVOlmvJA2R2t7yEu7cEtTfnf4PfZCg32Al9ug2TCzqFafjG7d/ROshC1zZo3OeK/GYERdXeeDw7uermxFLlJp8d3mV3YbhhY=
  app: meet-in-the-middle-react-front-end
  on:
    repo: gennyallcroft/meet-in-the-middle-react-front-end
